# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a4423c970b127667ee2bca150c495122b57dc4e4c3d8998f74a5163bf1057ef2feafb6f0f566e8f4e396a4bad8faff8d411d01bbd83082eb9f0ccc6a8be9930

test:
  secret_key_base: 6178c08b2ece5c1fbe4a46b4241b9fe662db2e9dda4ccee40155db06f002ad3a4c4793df8ff142169f69cff11c6ed9b7ad404e2b369c3f2b5f96d734c7f126f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
